#!/bin/bash/
#
#paarsuse kontroll
#
#skripti algus
echo -n "sisesta suvaline täisarv"
read arv
#
jaak=$(( $arv % 2))
# 4 % 2 =>  0 -> siis arv on paaris
# 5 % 2 =>  1 -> siis arv on paaritu
if [$jaak -eq 0]
then
	echo "$arv on paaris"
else
	echo "$arv on paaritu"
fi
# tingimus kontroll on lõppenud
#
#skripti lõpp
