#!/bin/bash
echo -n "Sisesta number: "
read num
i=2

while [ $i -le $num ]
do
	if [ 'expr $num % $i' -eq 0 ]
	then
		echo "$num ei ole alg arv"

	exit
	fi

	i='expr $i + 1'

done
echo " $num on algarv"
