#!/bin/bash
#
#reisist tagasi tuleku arvutamine
#
#skripti algus
echo "pyhapev - o, esmaspaev - 1, ..., laupaev - 6"
#kysime andmeid
echo -n "Sisesta millal soidad ara: "
read resi_soit
#palju reisid
echo -n "Sisesta reisi ööpäevade arv: "
read paev
#
#arvutused
#
#arvutame reisimise taisnadalate arv ja vaatame, palju reisipaevi jaab yle
veel_reisi_paevad=$(($paev % 7))
#jaanud paevad liidame reisi algusepevale
#
#sellega saaame kuna oleme tagasi
tagasi=$(($reis_soit + $veel_reisi_paevad))
#
#tulemuste valjastamine
echo "Tagasi oled paeva number $tagasi"
#skripti lõpp
